
<footer>
    <h1 class="logo-text">De fils en perles</h1>
    <ul>
        
        <li> <span><i class="fa fa-envelope"></i> jess@defilsenperles.com</span></li>
        <li> <p>Droit d'auteur © 2023 | De Fils En Perles</p></li>
      
    </ul>
    <ul>
        <li><a href ="/res03-projet-final/accueil"><i class="fab fa-instagram"></i></a></li>
        <li> <a href ="/res03-projet-final/accueil"><i class="fab fa-etsy"></i></a></li>
    </ul>
    
       
        
       
       
</footer>