<nav id = "navBar">
    <ul>
        <li class = "js"><a href ="/res03-projet-final/accueil"><figure><img src = "/res03-projet-final/assets/images/LOGOS-VISIO.png" alt="logo de file en perles"></figure></a></li>
        <li class = "js"><a href ="/res03-projet-final/accueil">ACCUEIL</a></li>
        <li class = "js"><a href ="/res03-projet-final/aPropos">A PROPOS</a></li>
        <li class = "js"><a href ="/res03-projet-final/contact">CONTACT</a></li>
        <li class = "js"><a href ="/res03-projet-final/produits" >BOUTIQUE</a></li>

       
    </ul>
    <ul>
        <li class = "js"><a href ="/res03-projet-final/monPanier">Mon Panier <i class="fa-solid fa-bag-shopping"></i></a></li>
        <li class = "js"><a href ="/res03-projet-final/login">CONNEXION</a></li>
        <li class = "js"><a href = "/res03-projet-final/register">INSCRIPTION</a></li>
        
    </ul>
    
    
</nav>