<nav id = "navBar">
    <ul>
        <li><a><figure><img></img</figure></a></li>
        <li><a href ="/res03-projet-final/accueil">Accueil</a></li>
        <li><a href ="/res03-projet-final/aPropos">A propos</a></li>
        <li><a href ="/res03-projet-final/contact">Contact</a></li>
        <li><a href ="/res03-projet-final/produits" >Galerie</a></li>
       
    </ul>
    <ul>
        <li><a href ="/res03-projet-final/login">Connexion</a></li>
        <li><a href = "/res03-projet-final/register">Inscription</a></li>
    </ul>
    
    
</nav>