<nav id = "navBarUser">
    <ul>
        <li class = "js"><a href ="/res03-projet-final/accueil"><figure><img src = "/res03-projet-final/assets/images/LOGOS-VISIO.png" alt="logo de file en perles"></figure></a></li>
        <li class = "js"><a href ="/res03-projet-final/accueil">ACCUEIL</a></li>
        <li class = "js"><a href ="/res03-projet-final/aPropos">A PROPOS</a></li>
        <li class = "js"><a href ="/res03-projet-final/contact">CONTACT</a></li>
        <li class = "js"><a href ="/res03-projet-final/produits" >GALERIE</a></li>
       
    </ul>
    <ul>
        <li class = "js"><a href ="/res03-projet-final/monPanier">Mon Panier <i class="fa-solid fa-bag-shopping"></i></a></li>
        <li class = "js"><a href ="/res03-projet-final/monPanier"><?php echo $_SESSION["username"] ?></a></li>
        <li class = "js"><a href = "/res03-projet-final/logout">DECONNEXION</a></li>
    </ul>
    
    
</nav>