<nav id = "navBarUser">
    <ul>
        <li><a><figure><img></img</figure></a></li>
        <li><a href ="/res03-projet-final/accueil">Accueil</a></li>
        <li><a href ="/res03-projet-final/aPropos">A propos</a></li>
        <li><a href ="/res03-projet-final/contact">Contact</a></li>
        <li><a href ="/res03-projet-final/produits" >Galerie</a></li>
       
    </ul>
    <ul>
        <li><a href ="/res03-projet-final/monPanier">Mon Panier</a></li>
        <li><a href ="/res03-projet-final/monPanier"><?php echo $_SESSION["username"] ?></a></li>
        <li><a href = "/res03-projet-final/logout">Deconnexion</a></li>
    </ul>
    
    
</nav>