<?php 


?>
<main class="adminProduits">
    
<table id = "imageProduits" class="table table-striped col-lg-6 table-bordered table-striped text-center">
    <h1>Gestion des Images</h1>
    <?php echo " <a href='/res03-projet-final/admin/produit/ajouter'><button>Créer un Produit</button></a>"; ?>
              <thead>
                     <tr >
                     <th>Id </th>
                     <th>Name</th>
                      <th>Description </th>
                      <th>PrixHT</th>
                      <th>Stock </th>
                      <th>Categorie</th>
                      <th>Materiau</th>
                      <th>Modifier </th>
                      <th>Supprimer </th>
                      <th>Images</th>
                        
                 </tr>
                 </thead>
                 <tbody>
                 <?php 
                   

                 foreach($data["products"]as $product){
                    //   var_dump($product->getPrix());
                     echo "<tr>";
                            echo "<td scope='row'>".$product->getId()."</td>";
                            echo "<td>".$product->getName()."</td>";
                            echo "<td>".$product->getDesciption()."</td>";
                            echo "<td>".$product->getPrix()."</td>";
                            echo "<td>".$product->getStock()."</td>";
                            echo "<td>".$product->getCategory()."</td>";
                            
                            echo "<td>";
                            foreach($product->getMaterials() as $material){
                                
                                echo "---".$material;
                                echo "<br>";
                                echo "<br>";
                            }
                        echo "<td> <a href='/res03-projet-final/admin/produit/".$product->getId()."/modifier'>Modifier</a></td>";
                        echo "<td> <a href='/res03-projet-final/admin/produit/".$product->getId()."/supprimer'>Supprimer</a></td>";

                            foreach ($product->getImages() as $key2 => $image) {
                            "</td>";
        
        echo "<td><figure><img src='/res03-projet-final/".$image."'></figure></td>";
    }
                     echo "</tr>";
                     
                     
                     
                 }
                 
                 
                 ?>
                 </tbody>
                 
             </table>
             
             </main>