<?php 


?> <main class="adminProduits">
  <table id="imageProduits" class="table table-striped col-lg-6 table-bordered table-striped text-center">
    <h1>Gestion des Produits</h1>  
		
		<a href='/res03-projet-final/admin/produit/ajouter'>
			<button>Créer un Produit</button>
		</a>" 
		<thead>
      <tr>
        <th>Id </th>
        <th>Name</th>
        <th>Description </th>
        <th>PrixHT</th>
        <th>Stock </th>
        <th>Categorie</th>
        <th>Materiau</th>
        <th>Modifier </th>
        <th>Supprimer </th>
        <th>Images</th>
      </tr>
    </thead>
    <tbody> <?php      foreach($data["products"]as $product){ ?> <tr>
        <td scope='row'> <?= $product->getId()  ?> </td>
        <td> <?= $product->getName() ?> </td>
        <td> <?= $product->getDesciption() ?> </td>
        <td> <?= $product->getPrix() ?> </td>
        <td> <?= $product->getStock() ?> </td>
        <td> <?= $product->getCategory() ?> </td>
        <td> <?php foreach($product->getMaterials() as $material){  ?> <?= $material ?> <br>
          <br> <?php   }  ?>
        <td>
          <a href='/res03-projet-final/admin/produit/
									<?= $product->getId() ?>/modifier'>Modifier </a>
        </td>
        <td>
          <a href='/res03-projet-final/admin/produit/
									<?= $product->getId() ?>/supprimer'>Supprimer </a>
        </td> <?php foreach ($product->getImages() as $key2 => $image) {  ?> </td>
        <td>
          <figure>
            <img src='/res03-projet-final/
									<?= $image  ?>'>
          </figure>
        </td> <?php    }  ?>
      </tr> <?php } ?> </tbody>
  </table>
</main>