
<section>
    
<?php
 
// var_dump($data["images"]);
foreach($data["products"] as $product){
    echo "<article>";
    
        foreach($data["images"] as $imageData){
             
          if($imageData["id"]=== $product->getId()){
              
              echo "<figure><img src=".$imageData[0]."></img></figure>";
          }
        // echo $imageData["name"];
        // echo  $product->getName();
 };
       echo "<ul>";
            echo "<li>";
            echo "nom : ".$product->getName();
            echo "</li>";
            echo "<li>";
            echo $product->getPrix()." euros";
            echo "</li>";
            echo "<li>";
            echo " desciprtion: ".$product->getDesciption();
            echo "</li>";
            echo "<li>";
            echo $product->getStock();
            echo "</li>";
            echo "<li>";
            echo $product->getCategory();
            echo "</li>";
            echo "<button>Ajouter au Panier</button>";
        echo "</ul>";
    echo "</article>";
}
?>

    
    
    
    
</section>