
<section>
   
<?php 

// var_dump($data["products"]);
foreach ($data["products"] as $key => $product) {
    
    echo "<article>";
    // var_dump($key);
    echo "<button class ='caroussel'>></button>";
    //   var_dump($product->getImages());
      echo "<header>";
    foreach ($product->getImages() as $key2 => $image) {
      
        echo "<a class=" .$key." href='produit/".$product->getId()."'>
                <figure>
                
                    <img src='/res03-projet-final/".$image."'>
                
                </figure></a>";
                
               
    }
 echo "</header>";
    echo "<ul>";
           
            // echo "<li>id: " . $product->getId()."</li>";
            echo "<li> nom: " . ucfirst($product->getName())."</li>";
            echo "<li>".$product->getCategory()."</li>";
            echo "<li>desciprtion: " .$product->getDesciption()."</li>";
            echo "<li>Prix: ".$product->getPrix() ." euros</li>";
            
          
    echo "<button product=".$product->getId()." class=paniers>Ajouter au Panier</button>";
    echo "</ul>";
    echo "</article>";
} ?>

    
    
 