<nav id = "navBarAdmin">
    <ul>
        <li><a><figure><img></img</figure></a></li>
        <li><a href ="/res03-projet-final/admin/categories">Categories</a></li>
        <li><a href ="/res03-projet-final/admin/utilisateurs">Produits</a></li>
        <li><a href ="/res03-projet-final/admin">Images</a></li>
        <li><a href ="/res03-projet-final/admin" >Order</a></li>
        <li><a href ="/res03-projet-final/admin" >Materiaux</a></li>
       
    </ul>
    
        
        <a href ="/res03-projet-final/produits">Retour au site</a></li>
      
        

    
    
</nav>