<nav id = "navBarAdmin">
    <ul>
        
        <li><a href ="/res03-projet-final/admin/categories">Categories</a></li>
        <li><a href ="/res03-projet-final/admin/produits">Produits</a></li>
        <li><a href ="/res03-projet-final/admin/images">Images</a></li>
        <li><a href ="/res03-projet-final/admin" >Commandes</a></li>
        <li><a href ="/res03-projet-final/admin/materiaux" >Materiaux</a></li>
        <li><a href ="/res03-projet-final/admin/utilisateurs" >Utilisateur</a></li>
       
    </ul>
    
        
        <a href ="/res03-projet-final/produits">Retour au site</a></li>
      
        

    
    
</nav>