<form action="/res03-projet-final/admin/categorie/ajouter" method="post">
  <h1>Création de categorie</h1>
  
  
  
  <fieldset>
  <label for="name">Nom de la Categorie</label>
  <input type="text" id="name" name="name">
  </fieldset>
  
  <input type="hidden" name="formName" value="createCategory">

  <button id="registerButton" type="submit" value="Creer l'utilisateur"><span class="fa-duotone fa-lock"></span>Creer la Categorie</button>
  
    </fieldset>
  <p>Revenir a la liste des categories<a href ="/res03-projet-final/admin/categories">ICI</a> </p>
</form>