<main>
    
    <h1>A propos de moi</h1>
    <ul>
        <li>
            <p>Bienvenue chez De Fil en Perles, une petite entreprise créée par une passionnée de bijoux faits maison. En tant que créatrice de bijoux autodidacte, j'offre une grande variété de boucles d'oreilles, bracelets, colliers et autres accessoires, tous faits à la main avec soin et attention aux détails.</p>
        </li>
        <li>
            <p>Chez De Fil en Perles, vous pouvez être sûr(e) de trouver des bijoux uniques et originaux qui reflètent votre style personnel. J'aime travailler avec une variété de matériaux tels que les pierres naturelles, le bois, le cuir, les perles, les coquillages et bien d'autres encore, pour créer des bijoux qui sont à la fois beaux et durables.</p>
        </li>
        <li>
            <p>En plus de mes bijoux, je propose également des décorations et bijoux en macramé, eux aussi fabriqués 100% maison. Cette technique artisanale de tissage de fils est idéale pour créer des pièces décoratives et fonctionnelles, comme des porte-clés, des porte-plantes, des suspensions murales, des bracelets et bien d'autres encore.
</p>
        </li>
        <li>
            <p>En tant que créatrice de bijoux passionnée, je suis toujours heureuse de travailler avec mes clients pour créer des bijoux uniques et personnalisés qui reflètent leur personnalité et leur style. Si vous cherchez un bijou fait main et personnalisé pour vous-même ou pour offrir en cadeau, vous êtes au bon endroit.</p>
        </li>
        <li>
            <p>N'hésitez pas à explorer ma boutique en ligne pour découvrir mes dernières créations. Si vous avez des questions ou des demandes spéciales, n'hésitez pas à me contacter. Je suis là pour vous aider à trouver le bijou parfait pour vous ou pour vos proches.</p>
        </li>
        
    </ul>
</main>