<!DOCTYPE html>
<html lang ="fr">
<head>
    <meta charset="utf-8" />
    <title>
        Le site dont vous êtes le héros
    </title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&family=Special+Elite&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/styles/css/style.css" />
</head>
<body id= <?php echo $template ?>>








</body>
</html>


<?php 



require 'templates/admin/partials/_admin-header.phtml';

require "templates/admin/".$template."/".$template.".phtml";

require 'templates/admin/partials/_admin-footer.phtml';
?>
