<form action="login" method="post">
  <h1>Connexion</h1>
  
  <fieldset>
  <label for="login">Email</label>
  <input type="email" id="login" name="login">
  </fieldset>
  
  <fieldset>
  <label for="password">Mot de passe</label>
  <input type="password" id="password" name="password">
  </fieldset>
  <input type="hidden" name="formName" value="login">
  
  
    <fieldset id="buttons">
  <input type="hidden" name="formName" value="login">

  <button id="registerButton" type="submit" value="Créer un compte">Connexion</button>
  
    </fieldset>
  <p>Pour s'incrire cliquez <a href ="/res03-projet-final/register">ICI</a> </p>
</form>
 <?php /*var_dump($_POST); */

?> 
