<form action="login" method="post" id = "login">
  <h2>Connexion</h2>
  <h3><?= $data[0]; ?></h3>
  <fieldset>
  <label for="email">Email</label>
  <input type="email" id="email" name="email">
  </fieldset>
  
  <fieldset>
  <label for="password">Mot de passe</label>
  <input type="password" id="password" name="password">
  </fieldset>
  <input type="hidden" name="formName" value="login">
  
  
    <fieldset id="buttons">
  <input type="hidden" name="formName" value="login">

  <button id="registerButton" type="submit" value="Créer un compte">Connexion<i class="fa-solid fa-right-to-bracket"></i></button>
  
    </fieldset>
  <p>Pour s'incrire cliquez <a href ="/res03-projet-final/register">ICI</a> </p>
</form>
 <?php /*var_dump($_POST); */

?> 
