<?php 
// var_dump($data);

?> <main class="justify-content-center">
  <table id="categoriesTable" class="table table-striped col-lg-6 table-bordered table-striped text-center">
    <h1>Gestion des Materiaux</h1> <?php echo "
		<a href='/res03-projet-final/admin/materiel/ajouter'>
			<button>Créer un Materiel</button>
		</a>" ?> <thead>
      <tr>
        <th>id </th>
        <th>name </th>
        <th>Detail </th>
        <th>Modifier </th>
        <th>Supprimer </th>
      </tr>
    </thead>
    <tbody> <?php    foreach($data["materials"]as $material){  ?> <tr>
        <td scope='row'> <?= $material->getId() ?> </td>
        <td> <?= $material->getName() ?> </td>
        <td>
          <a href='/res03-projet-final/admin/materiel'>X</a>
        </td>
        <td>
          <a href='/res03-projet-final/admin/materiel/
						<?= $material->getId() ?>/modifier'>Modifier </a>
        </td>
        <td>
          <a href='/res03-projet-final/admin/materiel/
						<?= $material->getId() ?>/supprimer'>Supprimer </a>
        </td>
      </tr> <?php   }  ?> </tbody>
  </table>
</main>