
<section>
    

<h2 class='sr-only'>Un Produit</h2>
    <article>
    <h2 class='sr-only'>Un article</h2>

        <button class ='caroussel'>></button>
        <?php    foreach($data["products"]->getImages() as $key2 => $image){ ?>
                
                
                <a class= 'image'><figure><img src='/res03-projet-final/<?=$image?>'  alt="Image produit"></figure></a>
                
         <?php    } ?>
         
      
      
 
       <ul>
       
            <li><p><span><?= $data["products"]->getName() ?></span></p></li>
            
            
            
            
         
            <li> <p>Description : <?= $data["products"]->getDesciption() ?></p></li>
            
           
            <li><p>Stock : <?= $data["products"]->getStock() ?></p></li>
            
           
            <li><p> <?= $data["products"]->getCategory() ?></p></li>
           
             <li><p>Materiaux : 
          <?php  foreach($data["products"]->getMaterials() as $material){ ?>
               <?= $material ?>
          <?php  }  ?>
            </p></li>
            <li><p>Prix : <?=$data["products"]->getPrix()?> €</p></li>
            <li><button id= <?= $data["products"]->getId()?> class=paniers>Ajouter au Panier</button></li>
        </ul>
    </article>

?>

    
    
    
    
</section>
