<form  method="post">
  <h1>Création de compte</h1>
    <fieldset>
  <label for="firstName">Username</label>
  <input type="text" id="registerUsername" name="registerUsername">
    </fieldset>
 
    <fieldset>
  <label for="email">Email</label>
  <input type="email" id="registerEmail" name="registerEmail">
    </fieldset>
    <fieldset>
  <label for="password">Mot de passe</label>
  <input type="password" id="registerPassword" name="registerPassword">
    </fieldset>
    <fieldset>
  <label for="confirmPassword">Confirmation du mot de passe</label>
  <input type="password" id="#" name="registerConfirmPwd">
    </fieldset>
    <fieldset id="buttons">
  <input type="hidden" name="formName" value="register">

  <button id="registerButton" type="submit" value="Créer un compte">Créer un compte</button>
  
<!--  <button id="button2" type="submit" value="Se connecter" href = "index.php?route=">Se connecter</button>-->
    </fieldset>
</form>
