<form  action = "register" method="post">
  <h2>Création de compte</h2>
    <fieldset>
  <label for="registerUsername">Identifiant</label>
  <input type="text" id="registerUsername" name="registerUsername">
    </fieldset>
 
    <fieldset>
  <label for="registerEmail">Email</label>
  <input type="email" id="registerEmail" name="registerEmail">
    </fieldset>
    <fieldset>
  <label for="registerPassword">Mot de passe</label>
  <input type="password" id="registerPassword" name="registerPassword">
    </fieldset>
    <fieldset>
  <label for="registerConfirmPwd">Confirmation du mot de passe</label>
  <input type="password" id="registerConfirmPwd" name="registerConfirmPwd">
    </fieldset>
    <fieldset>
  <label for="number">Numero de Telephone</label>
  <input type="number" id="number" name="number">
    </fieldset>
    <fieldset id="buttons">
  <input type="hidden" name="formName" value="register">

  <button id="registerButton" type="submit" value="Créer un compte">Créer un compte<i class="fa-solid fa-right-to-bracket"></i></button>
 
    </fieldset>
     <p>Pour se connecter cliquez <a href ="/res03-projet-final/login">ICI</a> </p>
</form>


<?php 
// var_dump($_POST);
?>
