<form action="/res03-projet-final/admin/materiel/ajouter" method="post">
  <h1>Création de Materiel</h1>
  
  
  
  <fieldset>
  <label for="name">Nom de du Materiel</label>
  <input type="text" id="name" name="name">
  </fieldset>
  
  <input type="hidden" name="formName" value="createMaterial">

  <button id="registerButton" type="submit" value="Creer le Materiel"><span class="fa-duotone fa-lock"></span>Creer le Materiel</button>
  
    </fieldset>
  <p>Revenir a la liste des Materiaux<a href ="/res03-projet-final/admin/materiaux">ICI</a> </p>
</form>