<section>
    
    <h2 class="logo-text">Contact</h2>
    <ul>
        
        <li>             <p>N'hésitez pas à explorer ma boutique en ligne pour découvrir mes dernières créations. Si vous avez des questions ou des demandes spéciales, n'hésitez pas à me contacter. Je suis là pour vous aider à trouver le bijou parfait pour vous ou pour vos proches.</p>
        <li> <span><i class="fa fa-envelope"></i> jess@defilsenperles.com</span></li>

      
    </ul>
    <ul>
        <li><a href ="/res03-projet-final/accueil"><i class="fab fa-instagram"></i></a></li>
        <li> <a href ="/res03-projet-final/accueil"><i class="fab fa-etsy"></i></a></li>
    </ul>
</section>