 <body class="cart-open">
        <main>

        </main>
        <aside>
            <header>
                <h2>Mon panier</h2>
                <p id="cart-total-price">Total : 59 $</p>
            </header>
            <main>
                <ul>

                </ul>
            </main>
            <footer>
                <a class="btn btn-cart-back" href="">Continuer mes achats</a>
                <a class="btn btn-cart-order" href="">Finaliser la commande</a>
            </footer>
        </aside>
        <script type="module" src="assets/javascript/main.js"></script>
    </body>