
<form action="/res03-projet-final/admin/materiel/<?php echo $data["toDisplay"]->getId() ?>/modifier" method="post">
  <h1>Modification de Materiaux</h1>
  
  <fieldset>
  <label for="id">id</label>
  <input type="number" id="id" name="id" readonly value= "<?php echo $data["toDisplay"]->getId() ?>">
  </fieldset>
  
  
  <fieldset>
  <label for="name">Nom de la Categorie</label>
  <input type="text" id="name" name="name" value= "<?php echo $data["toDisplay"]->getName() ?>">
  </fieldset>
  
  <input type="hidden" name="formName" value="updateCategory">

  <button id="registerButton" type="submit" value="ModifierMateriel"><span class="fa-duotone fa-lock"></span>Modifier le Materiel</button>
  
    </fieldset>
  <p>Revenir a la liste des Materiaux<a href ="/res03-projet-final/admin/materiaux">ICI</a> </p>
</form>